In [71]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
np.random.seed(0)
x=np.random.randn(100)
y=np.random.randn(100)
f=np.polyfit(x,y,3)
p=np.poly1d(f)

In [72]:
print(p)

          3          2
-0.01477 x - 0.0668 x + 0.1626 x + 0.1432


In [78]:
from sklearn.preprocessing import PolynomialFeatures
pr = PolynomialFeatures(degree = 2,include_bias=False)
x_polly = pr.fit_transform(flights[['year','passengers']])

In [79]:
print(x_polly)

[[1.949000e+03 1.120000e+02 3.798601e+06 2.182880e+05 1.254400e+04]
 [1.949000e+03 1.180000e+02 3.798601e+06 2.299820e+05 1.392400e+04]
 [1.949000e+03 1.320000e+02 3.798601e+06 2.572680e+05 1.742400e+04]
 [1.949000e+03 1.290000e+02 3.798601e+06 2.514210e+05 1.664100e+04]
 [1.949000e+03 1.210000e+02 3.798601e+06 2.358290e+05 1.464100e+04]
 [1.949000e+03 1.350000e+02 3.798601e+06 2.631150e+05 1.822500e+04]
 [1.949000e+03 1.480000e+02 3.798601e+06 2.884520e+05 2.190400e+04]
 [1.949000e+03 1.480000e+02 3.798601e+06 2.884520e+05 2.190400e+04]
 [1.949000e+03 1.360000e+02 3.798601e+06 2.650640e+05 1.849600e+04]
 [1.949000e+03 1.190000e+02 3.798601e+06 2.319310e+05 1.416100e+04]
 [1.949000e+03 1.040000e+02 3.798601e+06 2.026960e+05 1.081600e+04]
 [1.949000e+03 1.180000e+02 3.798601e+06 2.299820e+05 1.392400e+04]
 [1.950000e+03 1.150000e+02 3.802500e+06 2.242500e+05 1.322500e+04]
 [1.950000e+03 1.260000e+02 3.802500e+06 2.457000e+05 1.587600e+04]
 [1.950000e+03 1.410000e+02 3.802500e+06 2.74950

In [ ]:
# mean squared error 


In [80]:
from sklearn.metrics import mean_squared_error
flights=sns.load_dataset("Flights")


In [82]:
mean_squared_error(flights['year'],flights['passengers'])

2816493.326388889

In [83]:
mean_squared_error(flights['year'],flights['passengers'],multioutput='raw_values')

array([2816493.32638889])

In [87]:
mean_squared_error(flights['year'],flights['passengers'],multioutput='uniform_average')

2816493.326388889

In [88]:
mean_squared_error(
    flights['year'],
    flights['passengers']
)

2816493.326388889

In [92]:
x=flights[['year']]
y=flights[['passengers']]


In [93]:
lm=LinearRegression()

In [94]:
lm.fit(x,y)

LinearRegression()

In [95]:
lm.score(x,y)

0.8497591833132266